# Generated by Django 5.2.4 on 2025-07-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskInput', models.CharField(max_length=100)),
                ('startInput', models.DateField()),
                ('endInput', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
